app:
  build: ./app
  restart: always
  env_file: ./app/env
  ports:
    - "8000:8000"
    - "8100:8100"
  links:
    - mysql:db
    - redis:redis
  volumes:
    - ./app:/usr/src/app
  command: /usr/local/bin/gunicorn bms_backend.wsgi:application -w 2 -b 0.0.0.0:8000

app_frontend:
  build: ./app_frontend
  restart: always
  ports:
    - "8200:9000"
    - "8300:9100"
  tty: true
  volumes:
    - ./app_frontend:/usr/src/app_frontend
  command: npm run serve
  environment:
    PRODUCTION: 'true'

nginx:
  build: ./nginx
  restart: always
  ports:
    - "80:80"
  links:
    - app:app
    - app_frontend:frontend
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/ssl:/etc/nginx/ssl
    - ./nginx/development.conf:/etc/nginx/conf.d/development.conf
    - ./nginx/log:/var/log/nginx
    - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    - ./app_frontend/dist:/var/www/html
    - ./app_frontend/dist:/usr/src/app/test
    - ./app/static:/usr/src/app/static

mysql:
  build: ./mysql
  restart: always
  volumes:
    - ./mysql/backup:/tmp/backup
    - ./storage/volume:/var/lib/mysql
  ports:
    - "3306:3306"
  volumes_from:
    - storage

redis:
  image: redis:latest
  restart: always
  ports:
    - "6379:6379"
  volumes_from:
    - dev_storage
  command: redis-server --appendonly yes

storage:
  build: ./storage
