app:
  build: ./app
  restart: always
  env_file: ./app/env
  ports:
    - "8000:8000"
    - "8100:8100"
  links:
    - mysql:db
    - redis:redis
  volumes:
    - ./app:/usr/src/app
#  command: ./manage.py runserver 0.0.0.0:8000
  command: /usr/local/bin/gunicorn bms_backend.wsgi:application -w 2 -b :8000

app_frontend:
  build: ./app_frontend
  restart: always
  ports:
    - "9000:9000"
    - "9100:9100"
  links:
    - app:app
  volumes:
    - ./app_frontend:/usr/src/app_frontend
  command: npm run serve


nginx:
  build: ./nginx
  restart: always
  ports:
    - "80:80"
    - "443:443"
  links:
    - app:app
    - app_frontend:frontend
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/ssl:/etc/nginx/ssl
    - ./nginx/development.conf:/etc/nginx/conf.d/development.conf
    - ./nginx/log:/var/log/nginx
    - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
  volumes_from:
    - app
    - app_frontend

mysql:
  build: ./mysql
  restart: always
  volumes:
  - ./mysql/backup:/tmp/backup
  ports:
    - "3306:3306"
  volumes_from:
    - storage

redis:
  image: redis:latest
  restart: always
  ports:
    - "6379:6379"
  volumes_from:
    - storage
  command: redis-server --appendonly yes

storage:
  build: ./storage
