dev_app:
  build: ./app
  restart: always
  env_file: ./app/env
  ports:
    - "8000:8000"
  links:
    - dev_mysql:db
    - dev_redis:redis
  volumes:
    - C:\BMS\webapp\app:/usr/src/app
  # command: python3 manage.py runserver 0.0.0.0:8000
  command: /usr/local/bin/gunicorn bms_backend.wsgi:application -w 2 -b :8000
  tty: true

dev_app_frontend:
  build: ./app_frontend
  restart: always
  ports:
    - "9000:9000"
    - "9100:9100"
  # links:
  #   - dev_app
  volumes:
    - C:\BMS\webapp\app_frontend:/usr/src/app_frontend
  command: npm run serve
  tty: true


dev_nginx:
  build: ./nginx
  restart: always
  ports:
    - "80:80"
    - "443:443"
  links:
    - dev_app:app
    - dev_app_frontend:frontend
  volumes:
    - C:\BMS\webapp\nginx\nginx.conf:/etc/nginx/nginx.conf
    - C:\BMS\webapp\nginx\ssl:/etc/nginx/ssl
    - C:\BMS\webapp\nginx\development.conf:/etc/nginx/conf.d/development.conf
    - C:\BMS\webapp\nginx\log:/var/log/nginx
    - C:\BMS\webapp\nginx\uwsgi_params:/etc/nginx/uwsgi_params
    - C:\BMS\webapp\app_frontend\dist:/usr/dist
    - C:\BMS\webapp\app\static:/usr/src/app/static
  volumes_from:
    - dev_app
    - dev_app_frontend

dev_mysql:
  build: ./mysql
  restart: always
  volumes:
    - C:\BMS\webapp\mysql\backup:/tmp/backup
  # environment:
  #     MYSQL_DATABASE: bms_backend
  #     MYSQL_USER: bms_backend
  #     MYSQL_PASSWORD: password
  #     MYSQL_ROOT_PASSWORD: rootpassword
  ports:
    - "3306:3306"
  volumes_from:
    - dev_storage

dev_redis:
  image: redis:latest
  restart: always
  ports:
    - "6379:6379"
  volumes_from:
    - dev_storage
  command: redis-server --appendonly yes

dev_storage:
  build: ./storage
