dev_app:
  build: ./app
  restart: always
  env_file: ./app/env
  ports:
    - "8000:8000"
    # - "8100:8100"
  links:
    - dev_mysql:db
    - dev_redis:redis
  volumes:
    - ./app:/usr/src/app
  command: ./manage.py runserver 0.0.0.0:8000
  # command: /usr/local/bin/gunicorn bms_backend.wsgi:application -w 2 -b 0.0.0.0:8000
  # command: ./manage.py 

dev_app_frontend:
  build: ./app_frontend
  restart: always
  ports:
    - "9000:9000"
    - "9100:9100"
  tty: true
  volumes:
    - ./app_frontend:/usr/src/app_frontend
  # command: bash -c "npm run serve && vue ui --port 9100 --host 0.0.0.0"
  command: npm run serve

dev_nginx:
  build: ./nginx
  restart: always
  ports:
    - "80:80"
    # - "443:443"
  links:
    - dev_app:app
    - dev_app_frontend:frontend
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/ssl:/etc/nginx/ssl
    - ./nginx/development.conf:/etc/nginx/conf.d/development.conf
    - ./nginx/log:/var/log/nginx
    - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    - ./app_frontend/dist:/var/www/html
    - ./app/static:/usr/src/app/static

dev_mysql:
  build: ./mysql
  restart: always
  volumes:
    - ./mysql/backup:/tmp/backup
    - ./mysql/settings/my.cnf:/etc/mysql/my.cnf
    - ./storage/volume:/var/lib/mysql
  ports:
    - "3306:3306"
  volumes_from:
    - dev_storage

dev_redis:
  image: redis:latest
  restart: always
  ports:
    - "6379:6379"
  volumes_from:
    - dev_storage
  command: redis-server --appendonly yes

dev_storage:
  build: ./storage
