dev_app:
  build: ./app
  restart: always
  env_file: ./app/env
  ports:
    - "8000:8000"
  links:
    - dev_mysql:db
    - dev_redis:redis
  volumes:
    - ./app:/usr/src/app
  command: ./manage.py runserver 0.0.0.0:8000

dev_app_frontend:
  build: ./app_frontend
  restart: always
  ports:
    - "9000:9000"
    - "9100:9100"
  links:
    - dev_app
  volumes:
    - ./app_frontend:/usr/src/app_frontend
  command: vue ui -p 9100
  


#dev_nginx:
#  build: ./nginx
#  restart: always
#  ports:
#    - "80:80"
#    - "443:443"
#  links:
#    - dev_app:app
#  volumes:
#    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    - ./nginx/ssl:/etc/nginx/ssl
#    - ./nginx/development.conf:/etc/nginx/conf.d/development.conf
#  volumes_from:
#    - dev_app

dev_mysql:
  build: ./mysql
  restart: always
  ports:
    - "3306:3306"
  volumes_from:
    - dev_storage

dev_redis:
  image: redis:latest
  restart: always
  ports:
    - "6379:6379"
  volumes_from:
    - dev_storage
  command: redis-server --appendonly yes

dev_storage:
  build: ./storage
