# Generated by Django 3.1 on 2020-12-15 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_master', '0009_systemexpensecategory_abbr'),
        ('system_users', '0020_usercompany_time_charge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Parts name')),
                ('standard', models.CharField(blank=True, max_length=255, verbose_name='Standard・Model')),
                ('material', models.CharField(blank=True, max_length=255, verbose_name='Material')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_standard_inventory', models.BooleanField(default=False, verbose_name='is Standard Invontory')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='is Disabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_users.usercompany')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventorymaster_requests_created', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventorymaster_requests_manufacturer', to='system_users.userpartner')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventorymaster_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_master.systemunittype')),
            ],
        ),
    ]
