# Generated by Django 3.1 on 2020-12-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0002_auto_20201216_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaster',
            name='standard',
            field=models.CharField(max_length=255, verbose_name='Standard・Model'),
        ),
    ]
