# Generated by Django 3.1 on 2020-12-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0004_locationmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmaster',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='is Disabled'),
        ),
    ]
