# Generated by Django 3.1 on 2020-12-21 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system_master', '0009_systemexpensecategory_abbr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_data', '0005_locationmaster_is_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='InStockParts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apply_amount', models.DecimalField(decimal_places=2, default=1, max_digits=17, verbose_name='Apply amount')),
                ('used_amount', models.DecimalField(decimal_places=2, default=1, max_digits=17, verbose_name='Used amount')),
                ('rate', models.FloatField(default=1, verbose_name='Order Rate')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Unit Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instockparts_requests_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_master.systemcurrency')),
                ('inventory_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_data.inventorymaster')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_data.locationmaster')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instockparts_requests_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'in_stock_parts',
            },
        ),
    ]
