# Generated by Django 3.1 on 2020-12-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0006_instockparts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instockparts',
            name='used_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Used amount'),
        ),
    ]
