# Generated by Django 2.0.8 on 2018-11-26 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='country name')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='country code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
            ],
            options={
                'db_table': 'system_country',
            },
        ),
        migrations.CreateModel(
            name='SystemCurrency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='currency name')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='currency code')),
                ('display', models.CharField(max_length=10, unique=True, verbose_name='currency display')),
                ('decimal_point', models.IntegerField(verbose_name='decimal point')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
            ],
            options={
                'db_table': 'system_currency',
            },
        ),
        migrations.CreateModel(
            name='SystemUnitType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='unit type name')),
                ('display', models.CharField(max_length=50, unique=True, verbose_name='unit type display')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
            ],
            options={
                'db_table': 'system_unit_type',
            },
        ),
    ]
