# Generated by Django 2.1.7 on 2019-03-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemunittype',
            name='number',
            field=models.IntegerField(default=0, unique=True, verbose_name='number'),
            preserve_default=False,
        ),
    ]
