# Generated by Django 2.1.7 on 2019-03-14 23:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system_master', '0002_systemunittype_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_number', models.IntegerField(unique=True, verbose_name='Category number')),
                ('category_name', models.CharField(max_length=150, verbose_name='Category name')),
                ('is_processed_parts', models.BooleanField(default=False, verbose_name='is Processed parts')),
                ('is_active', models.BooleanField(default=True, verbose_name='is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
            ],
            options={
                'verbose_name': 'System Expense Category',
                'verbose_name_plural': 'System Expense Categories',
                'db_table': 'system_expense_categories',
            },
        ),
    ]
