# Generated by Django 2.1.7 on 2019-03-14 23:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system_master', '0003_systemexpensecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFailureCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_number', models.IntegerField(unique=True, verbose_name='Category number')),
                ('category_name', models.CharField(max_length=150, verbose_name='Category name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
            ],
            options={
                'verbose_name': 'System Failure Category',
                'verbose_name_plural': 'System Failure Categories',
                'db_table': 'system_failure_category',
            },
        ),
    ]
