# Generated by Django 2.1.7 on 2019-07-02 23:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system_master', '0004_systemfailurecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemJobType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(unique=True, verbose_name='Work Type number')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Work Type name')),
                ('is_calculate', models.BooleanField(default=True, verbose_name='is Calculate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
            ],
            options={
                'verbose_name': 'System Job Type',
                'verbose_name_plural': 'System Job Types',
                'db_table': 'system_job_type',
            },
        ),
        migrations.AlterField(
            model_name='systemexpensecategory',
            name='category_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='systemfailurecategory',
            name='category_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Category name'),
        ),
    ]
