# Generated by Django 2.1.7 on 2019-07-02 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_master', '0005_systemworktypemaster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemWorkTypeMaster',
            new_name='SystemWorkType',
        ),
    ]
