# Generated by Django 2.1.7 on 2019-07-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_master', '0006_systemjobtype_abbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemjobtype',
            name='abbr',
            field=models.CharField(blank=True, max_length=10, verbose_name='Abbreviation'),
        ),
    ]
