# Generated by Django 2.1.7 on 2019-07-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_master', '0007_auto_20190703_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemexpensecategory',
            name='is_calculate',
            field=models.BooleanField(default=True, verbose_name='is Calculate in WIP'),
        ),
    ]
