# Generated by Django 2.1.7 on 2019-07-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_master', '0008_systemexpensecategory_is_calculate'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemexpensecategory',
            name='abbr',
            field=models.CharField(blank=True, max_length=10, verbose_name='Abbreviation'),
        ),
    ]
