# Generated by Django 2.0.5 on 2018-09-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system_users.UserStaff'),
        ),
    ]
