# Generated by Django 2.0.5 on 2018-09-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0002_auto_20180905_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
