# Generated by Django 2.0.8 on 2018-12-27 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0003_auto_20181225_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_number', models.IntegerField(verbose_name='partner number')),
                ('name', models.CharField(max_length=150, verbose_name='Partner name')),
                ('abbr', models.CharField(blank=True, max_length=150, verbose_name='Abbreviation')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone number')),
                ('fax', models.CharField(blank=True, max_length=15, verbose_name='Fax number')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal code')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('is_client', models.BooleanField(verbose_name='is client')),
                ('is_delivery_destination', models.BooleanField(verbose_name='is delivery estination')),
                ('is_supplier', models.BooleanField(verbose_name='is supplier')),
                ('is_manufacturer', models.BooleanField(verbose_name='is Manufacturer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_users.UserCompany')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userpartner_requests_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userpartner_requests_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
                'db_table': 'Partner',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userpartner',
            unique_together={('company', 'partner_number')},
        ),
    ]
