# Generated by Django 2.0.5 on 2018-09-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstaff',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='userstaff',
            name='is_login_user',
            field=models.BooleanField(default=True, help_text='Designates whether the user can create login user.', verbose_name='login status'),
        ),
    ]
