# Generated by Django 2.0.8 on 2019-01-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0004_auto_20181227_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpartner',
            name='is_delivery_destination',
            field=models.BooleanField(verbose_name='is delivery destination'),
        ),
    ]
