# Generated by Django 2.0.8 on 2019-01-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0005_auto_20190103_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpartner',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userpartner',
            name='is_client',
            field=models.BooleanField(verbose_name='is Client'),
        ),
        migrations.AlterField(
            model_name='userpartner',
            name='is_delivery_destination',
            field=models.BooleanField(verbose_name='is Delivery destination'),
        ),
        migrations.AlterField(
            model_name='userpartner',
            name='is_supplier',
            field=models.BooleanField(verbose_name='is Supplier'),
        ),
        migrations.AlterField(
            model_name='userpartner',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
    ]
