# Generated by Django 2.0.8 on 2019-01-09 18:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0007_auto_20190103_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExpenceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=150, verbose_name='Category name')),
                ('category_number', models.IntegerField(verbose_name='Category number')),
                ('is_active', models.BooleanField(default=True, verbose_name='is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_users.UserCompany')),
            ],
            options={
                'verbose_name': 'expense_category',
                'verbose_name_plural': 'expense_categories',
                'db_table': 'expense_category',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userexpencecategory',
            unique_together={('company', 'category_number')},
        ),
    ]
