# Generated by Django 2.0.8 on 2019-01-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0008_auto_20190109_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExpenceCategory',
            new_name='UserExpenseCategory',
        ),
    ]
