# Generated by Django 2.0.8 on 2019-01-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0009_auto_20190109_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userexpensecategory',
            options={'verbose_name': 'Expense Category', 'verbose_name_plural': 'Expense Categories'},
        ),
    ]
