# Generated by Django 2.0.8 on 2019-02-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0011_auto_20190109_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpartner',
            name='is_client',
        ),
        migrations.AddField(
            model_name='userpartner',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='is Customer'),
        ),
    ]
