# Generated by Django 2.1.7 on 2019-03-09 23:09

from django.db import migrations, models
import django.db.models.deletion
import system_users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0012_auto_20190209_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFailureCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('failure_number', models.IntegerField(verbose_name='Failure number')),
                ('failure_name', models.CharField(max_length=150, verbose_name='Failure name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_users.UserCompany')),
            ],
            options={
                'verbose_name': 'Failure Category',
                'verbose_name_plural': 'Failure Categories',
                'db_table': 'failure_category',
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', system_users.models.UserAccountManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userfailurecategory',
            unique_together={('company', 'failure_number')},
        ),
    ]
