# Generated by Django 2.1.7 on 2019-03-09 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0013_auto_20190309_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfailurecategory',
            old_name='failure_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='userfailurecategory',
            old_name='failure_number',
            new_name='category_number',
        ),
        migrations.AlterUniqueTogether(
            name='userfailurecategory',
            unique_together={('company', 'category_number')},
        ),
    ]
