# Generated by Django 2.1.7 on 2019-03-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0014_auto_20190309_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfailurecategory',
            name='is_processed_parts',
            field=models.BooleanField(default=False, verbose_name='is Processed parts'),
        ),
        migrations.AlterField(
            model_name='userfailurecategory',
            name='category_name',
            field=models.CharField(max_length=150, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='userfailurecategory',
            name='category_number',
            field=models.IntegerField(verbose_name='Category number'),
        ),
    ]
