# Generated by Django 2.1.7 on 2019-03-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0015_auto_20190310_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfailurecategory',
            name='is_processed_parts',
        ),
        migrations.AddField(
            model_name='userexpensecategory',
            name='is_processed_parts',
            field=models.BooleanField(default=False, verbose_name='is Processed parts'),
        ),
    ]
