# Generated by Django 2.1.7 on 2019-03-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0016_auto_20190310_0324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userexpensecategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userexpensecategory',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='userfailurecategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userfailurecategory',
            name='company',
        ),
        migrations.DeleteModel(
            name='UserExpenseCategory',
        ),
        migrations.DeleteModel(
            name='UserFailureCategory',
        ),
    ]
