# Generated by Django 2.1.7 on 2019-04-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0017_auto_20190315_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='logo_data',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='logo'),
        ),
    ]
