# Generated by Django 2.1.7 on 2019-04-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0018_usercompany_logo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpartner',
            name='is_related_party',
            field=models.BooleanField(default=False, verbose_name='is Related party'),
        ),
    ]
