# Generated by Django 2.1.7 on 2019-07-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0019_userpartner_is_related_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='time_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Time Charge'),
        ),
    ]
