# Generated by Django 3.1 on 2020-12-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0020_usercompany_time_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpartner',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fax number'),
        ),
        migrations.AlterField(
            model_name='userpartner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone number'),
        ),
    ]
