FROM mysql:5.6

ENV MYSQL_DATABASE "bms_backend"
# ENV MYSQL_USER "bms_backend"
# ENV MYSQL_PASSWORD "test1357"
# ENV MYSQL_ROOT_PASSWORD ""
ENV MYSQL_ALLOW_EMPTY_PASSWORD "yes"


COPY charset.cnf /etc/mysql/conf.d/
