# Generated by Django 2.0.8 on 2019-02-06 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_users', '0011_auto_20190109_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mfg_no', models.CharField(max_length=20, verbose_name='Manufacturing Number')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('order_rate', models.FloatField(default=1, verbose_name='Order Rate')),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Order Price')),
                ('tax_percent', models.IntegerField(verbose_name='Tax Percentage')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Order Date')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_users.UserCompany')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='joborder_requests_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='joborder_requests_client', to='system_users.UserPartner')),
                ('delivery_destination', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='joborder_requests_delivery_destination', to='system_users.UserPartner')),
                ('designer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='joborder_requests_designer', to='system_users.UserStaff')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='joborder_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('order_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_master.SystemCurrency')),
                ('publisher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='joborder_requests_publisher', to='system_users.UserStaff')),
            ],
            options={
                'verbose_name': 'Job Order',
                'verbose_name_plural': 'Job Order',
                'db_table': 'job_order',
            },
        ),
        migrations.AlterUniqueTogether(
            name='joborder',
            unique_together={('company', 'mfg_no')},
        ),
    ]
