# Generated by Django 2.0.8 on 2019-02-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0002_auto_20190206_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='commercial_parts_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Commercial parts budget'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='electrical_parts_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Electrical parts budget'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='processed_parts_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Processed parts budget'),
        ),
    ]
