# Generated by Django 2.0.8 on 2019-02-21 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0004_auto_20190206_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='joborder_requests_publisher', to='system_users.UserStaff'),
        ),
    ]
