# Generated by Django 2.1.7 on 2019-03-09 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0005_auto_20190221_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Bill of Material',
                'verbose_name_plural': 'Bill of Material',
                'db_table': 'bill_of_material',
            },
        ),
    ]
