# Generated by Django 2.1.7 on 2019-03-12 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_master', '0002_systemunittype_number'),
        ('system_users', '0016_auto_20190310_0324'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manufacturing_data', '0006_billofmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='company',
            field=models.ForeignKey(default='934b0f1c-099b-4c07-a6df-75c894659048', on_delete=django.db.models.deletion.PROTECT, to='system_users.UserCompany'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2019-03-08T05:31:16.415111', verbose_name='created time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='created_by',
            field=models.ForeignKey(default='1f3cc4b7-c215-4011-a379-f6fa1a16f530', on_delete=django.db.models.deletion.PROTECT, related_name='billofmaterial_requests_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='currency',
            field=models.ForeignKey(default='3e412209-c1d8-4a72-8f34-6d0e590498ad', on_delete=django.db.models.deletion.PROTECT, to='system_master.SystemCurrency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='desired_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Desired delivery date'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='drawing_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Drawing Number'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='failure',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='system_users.UserFailureCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='is_customer_supplied',
            field=models.BooleanField(default=False, verbose_name='is Customer supplied'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='is Printed'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='billofmaterial_requests_manufacturer', to='system_users.UserPartner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='material',
            field=models.CharField(blank=True, max_length=255, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='modified_by',
            field=models.ForeignKey(default='1f3cc4b7-c215-4011-a379-f6fa1a16f530', on_delete=django.db.models.deletion.PROTECT, related_name='billofmaterial_requests_modified', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Parts name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=17, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='rate',
            field=models.FloatField(default=1, verbose_name='Order Rate'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='standard',
            field=models.CharField(blank=True, max_length=255, verbose_name='Standard・Model'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='stock_appropriation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='surface_treatment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Surface treatment'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='unit',
            field=models.ForeignKey(default='466f895b-13b1-44d4-b1be-868bd6cc7674', on_delete=django.db.models.deletion.PROTECT, to='system_master.SystemUnitType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='unit_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Unit Number'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='joborder_requests_customer', to='system_users.UserPartner'),
        ),
    ]
