# Generated by Django 2.1.7 on 2019-03-13 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0016_auto_20190310_0324'),
        ('manufacturing_data', '0007_auto_20190312_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='type',
            field=models.ForeignKey(default='52485ebc-ed0d-4a79-9acb-711f22a51018', on_delete=django.db.models.deletion.PROTECT, to='system_users.UserExpenseCategory'),
            preserve_default=False,
        ),
    ]
