# Generated by Django 2.1.7 on 2019-03-14 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0009_auto_20190314_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='system_users.UserFailureCategory'),
        ),
    ]
