# Generated by Django 2.1.7 on 2019-03-14 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0010_auto_20190314_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterial',
            name='company',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='failure',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='type',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='unit',
        ),
        migrations.DeleteModel(
            name='BillOfMaterial',
        ),
    ]
