# Generated by Django 2.1.7 on 2019-03-14 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0016_auto_20190310_0324'),
        ('system_master', '0004_systemfailurecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manufacturing_data', '0011_auto_20190314_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Parts name')),
                ('standard', models.CharField(blank=True, max_length=255, verbose_name='Standard・Model')),
                ('drawing_number', models.CharField(blank=True, max_length=255, verbose_name='Drawing Number')),
                ('material', models.CharField(blank=True, max_length=255, verbose_name='Material')),
                ('surface_treatment', models.CharField(blank=True, max_length=255, verbose_name='Surface treatment')),
                ('unit_number', models.CharField(blank=True, max_length=255, verbose_name='Unit Number')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=17, verbose_name='Quantity')),
                ('stock_appropriation', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Quantity')),
                ('rate', models.FloatField(default=1, verbose_name='Order Rate')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Unit Price')),
                ('desired_delivery_date', models.DateField(blank=True, null=True, verbose_name='Desired delivery date')),
                ('is_customer_supplied', models.BooleanField(default=False, verbose_name='is Customer supplied')),
                ('is_printed', models.BooleanField(default=False, verbose_name='is Printed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_users.UserCompany')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billofmaterial_requests_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_master.SystemCurrency')),
                ('failure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='system_master.SystemFailureCategory')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billofmaterial_requests_manufacturer', to='system_users.UserPartner')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billofmaterial_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_master.SystemExpenseCategory')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_master.SystemUnitType')),
            ],
            options={
                'verbose_name': 'Bill of Material',
                'verbose_name_plural': 'Bill of Material',
                'db_table': 'bill_of_material',
            },
        ),
    ]
