# Generated by Django 2.1.7 on 2019-03-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0013_billofmaterial_job_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='stock_appropriation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Stock appropriation'),
        ),
    ]
