# Generated by Django 2.1.7 on 2019-03-16 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0015_auto_20190315_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='joborder_requests_customer', to='system_users.UserPartner'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='delivery_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='joborder_requests_delivery_destination', to='system_users.UserPartner'),
        ),
    ]
