# Generated by Django 2.1.7 on 2019-04-10 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_users', '0017_auto_20190315_0001'),
        ('system_master', '0004_systemfailurecategory'),
        ('manufacturing_data', '0016_auto_20190316_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='partner number')),
                ('name', models.CharField(max_length=255, verbose_name='Parts name')),
                ('standard', models.CharField(blank=True, max_length=255, verbose_name='Standard・Model')),
                ('unit_number', models.CharField(blank=True, max_length=255, verbose_name='Unit Number')),
                ('drawing_number', models.CharField(blank=True, max_length=255, verbose_name='Drawing Number')),
                ('material', models.CharField(blank=True, max_length=255, verbose_name='Material')),
                ('surface_treatment', models.CharField(blank=True, max_length=255, verbose_name='Surface treatment')),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=17, verbose_name='Amount')),
                ('rate', models.FloatField(default=1, verbose_name='Order Rate')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Unit Price')),
                ('desired_delivery_date', models.DateField(blank=True, null=True, verbose_name='Desired delivery date')),
                ('is_printed', models.BooleanField(default=False, verbose_name='is Printed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('bill_of_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing_data.BillOfMaterial')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_users.UserCompany')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='makingorder_requests_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_master.SystemCurrency')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='makingorder_requests_manufacturer', to='system_users.UserPartner')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='makingorder_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_master.SystemUnitType')),
            ],
            options={
                'verbose_name': 'Making Order',
                'verbose_name_plural': 'Making Orders',
                'db_table': 'making_order',
            },
        ),
        migrations.AlterUniqueTogether(
            name='makingorder',
            unique_together={('company', 'number')},
        ),
    ]
