# Generated by Django 2.1.7 on 2019-04-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0017_auto_20190410_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='makingorder',
            name='ordered_date',
            field=models.DateField(blank=True, null=True, verbose_name='PO date'),
        ),
    ]
