# Generated by Django 2.1.7 on 2019-04-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0018_makingorder_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makingorder',
            name='number',
            field=models.IntegerField(verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='makingorder',
            name='ordered_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='PO date'),
        ),
    ]
