# Generated by Django 2.1.7 on 2019-04-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0019_auto_20190410_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makingorder',
            name='number',
            field=models.IntegerField(blank=True, verbose_name='number'),
        ),
    ]
