# Generated by Django 2.1.7 on 2019-04-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0020_auto_20190411_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makingorder',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='number'),
        ),
    ]
