# Generated by Django 2.1.7 on 2019-04-11 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0021_auto_20190411_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makingorder',
            name='bill_of_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing_data.BillOfMaterial', unique=True),
        ),
    ]
