# Generated by Django 2.1.7 on 2019-04-11 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0022_auto_20190411_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makingorder',
            name='bill_of_material',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing_data.BillOfMaterial'),
        ),
    ]
