# Generated by Django 2.1.7 on 2019-04-11 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0017_auto_20190315_0001'),
        ('manufacturing_data', '0023_auto_20190411_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='makingorder',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='makingorder_requests_supplier', to='system_users.UserPartner'),
        ),
    ]
