# Generated by Django 2.1.7 on 2019-04-16 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system_master', '0004_systemfailurecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manufacturing_data', '0024_makingorder_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=17, verbose_name='Amount')),
                ('rate', models.FloatField(default=1, verbose_name='Rate')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Unit Price')),
                ('received_date', models.DateField(blank=True, default=None, null=True, verbose_name='Received date')),
                ('is_received', models.BooleanField(default=False, verbose_name='is Received')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivingprocess_requests_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_master.SystemCurrency')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivingprocess_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing_data.MakingOrder')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_master.SystemUnitType')),
            ],
            options={
                'verbose_name': 'Receiving Process',
                'verbose_name_plural': 'Receiving Process',
                'db_table': 'receiving_process',
            },
        ),
    ]
