# Generated by Django 2.1.7 on 2019-04-16 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0025_receivingprocess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivingprocess',
            options={'verbose_name': 'Receiving Processes', 'verbose_name_plural': 'Receiving Process'},
        ),
    ]
