# Generated by Django 2.1.7 on 2019-04-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0026_auto_20190416_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='related_party_mfg_no',
            field=models.CharField(blank=True, max_length=20, verbose_name="Related party's MFG No"),
        ),
    ]
