# Generated by Django 2.1.7 on 2019-04-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0028_auto_20190422_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivingprocess',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='receivingprocess',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Unit Price'),
        ),
    ]
