# Generated by Django 2.1.7 on 2019-06-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0029_auto_20190422_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingprocess',
            name='suspense_received_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Suspense Received date'),
        ),
    ]
