# Generated by Django 2.1.7 on 2019-07-02 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0031_manhour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manhour',
            old_name='unit_price',
            new_name='work_hour',
        ),
    ]
