# Generated by Django 2.1.7 on 2019-07-04 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system_master', '0007_auto_20190703_2307'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manufacturing_data', '0032_joborder_bill_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectCostBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Order Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directcostbudget_requests_created', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing_data.JobOrder')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directcostbudget_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_master.SystemExpenseCategory')),
            ],
            options={
                'verbose_name': 'Direct Cost Budget',
                'verbose_name_plural': 'Direct Cost Budget',
                'db_table': 'direct_cost_budget',
            },
        ),
        migrations.AlterUniqueTogether(
            name='directcostbudget',
            unique_together={('job_order', 'type')},
        ),
    ]
