# Generated by Django 2.1.7 on 2019-07-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0033_auto_20190704_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='direct_cost_budget',
            field=models.ManyToManyField(blank=True, to='manufacturing_data.DirectCostBudget'),
        ),
    ]
