# Generated by Django 2.1.7 on 2019-07-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0034_joborder_direct_cost_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joborder',
            name='direct_cost_budget',
        ),
    ]
