# Generated by Django 2.1.7 on 2019-07-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0035_remove_joborder_direct_cost_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='assembly_budget_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Assembly budget hours'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='electrical_design_budget_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Electrical Design budget hours'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='electrical_wiring_budget_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Electrical Wiring budget hours'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='installation_budget_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Installation budget hours'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='mechanical_design_budget_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Mechanical Design budget hours'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='outsourcing_electrical_design_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Outsourcing Electrical Design budget'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='outsourcing_mechanical_design_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Outsourcing Mechanical Design budget'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='outsourcing_other_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Outsourcing - Other budget'),
        ),
    ]
