# Generated by Django 2.1.7 on 2019-07-16 01:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0036_auto_20190704_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='shipping_cost_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=17, verbose_name='Shipping Cost budget'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='shipping_cost_result',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=17, verbose_name='Shipping Cost result'),
        ),
    ]
