# Generated by Django 2.2.5 on 2019-12-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_data', '0037_auto_20190716_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
